---
- name: install nc
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - yum:
      name: nc
      state: latest

- name: ds port check
  hosts: ds:ds_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 2181, 2888, 3888, 7000, 9042, 9160, 7199 ] 
    clients: "{{ groups['ds'] + groups['ds_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ds port check for client
  hosts: ds
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 2181, 9042, 9160 ]   
    clients: "{{ groups['ms'] + groups['rpm'] + groups['qs'] + groups['ps'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ds port check for client (dr)
  hosts: ds_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 2181, 9042, 9160 ]   
    clients: "{{ groups['ms_dr'] + groups['rpm_dr'] + groups['qs_dr'] + groups['ps_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ld port check
  hosts: ld
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 10389 ]   
    clients: "{{ groups['ms'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ld port check (dr)
  hosts: ld_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 10389 ]   
    clients: "{{ groups['ms_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ld port check for multi dc
  hosts: ld:ld_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 10389 ]   
    clients: "{{ groups['ld'] + groups['ld_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }         

- name: ms port check
  hosts: ms
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 8080, 8443 ]
    clients: "{{ groups['rpm'] + groups['qs'] + groups['ps'] + groups['dp'] + groups['sso'] + groups['ue'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ms port check (dr)
  hosts: ms_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 8080, 8443 ]
    clients: "{{ groups['rpm_dr'] + groups['qs_dr'] + groups['ps_dr'] + groups['dp_dr'] + groups['sso_dr'] + groups['ue_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }  

- name: ms port check for multi dc
  hosts: ms:ms_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4526, 8080, 8443 ]
    clients: "{{ groups['ms'] + groups['ms_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: rpm port check
  hosts: rpm
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4527, 4528, 8081, 8082, 8998 ]
    clients: "{{ groups['rpm'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: rpm port check (dr)
  hosts: rpm_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4527, 4528, 8081, 8082, 8998 ]
    clients: "{{ groups['rpm_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: rpm port check for multi dc
  hosts: rpm:rpm_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4528 ]
    clients: "{{ groups['rpm'] + groups['rpm_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }    

- name: rpm port check for ms
  hosts: rpm:rpm_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4527, 4528, 8081, 8082 ]
    clients: "{{ groups['ms'] + groups['ms_dr']}}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: qs port check
  hosts: qs
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 5672 ]
    clients: "{{ groups['rpm'] + groups['qs'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: qs port check (dr)
  hosts: qs_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 5672 ]
    clients: "{{ groups['rpm_dr'] + groups['qs_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }  

- name: qs port check for multi dc
  hosts: qs:qs_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 5672 ]
    clients: "{{ groups['qs'] + groups['qs_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: qs port check for ms
  hosts: qs:qs_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4529, 8083 ]
    clients: "{{ groups['ms'] + groups['ms_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }

- name: ps port check
  hosts: ps:ps_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 5432 ]
    clients: "{{ groups['ms'] + groups['qs'] + groups['ps'] + groups['dp'] + groups['sso'] + groups['ms_dr'] + groups['qs_dr'] + groups['ps_dr'] + groups['dp_dr'] + groups['sso_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }  

- name: ps port check for ms
  hosts: ps:ps_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 4530, 8084 ]
    clients: "{{ groups['ms'] + groups['ms_dr']}}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }  

- name: sso port check
  hosts: sso:sso_dr
  gather_facts: false
  strategy: free
  vars:
    listeners: [ 9090 ]
    clients: "{{ groups['ms'] + groups['sso'] + groups['ms_dr'] + groups['sso_dr'] }}"
  roles:
  - { role: apigee-port-check, ports: "{{ listeners }}", nodes: "{{ clients }}" }