---
- name: Setup listener
  shell: "nc -lk -p {{ item }}"
  with_items: "{{ ports }}"
  when: "{{ enable_listener | default(true) | bool }}"
  async: 10
  poll: 0


- name: Validate port
  wait_for:
    port: "{{ item.1 }}"
    timeout: "{{ timeout_port | default(10) }}"
    host: "{{ inventory_hostname }}"
  delegate_to: "{{ item.0 }}"
  with_nested:
  - "{{ nodes }}"  
  - "{{ ports }}"
  
- name: Clean listener
  shell: "pkill -9 nc"
  when: "{{ enable_listener }}"